# Generated by Django 4.2.2 on 2023-06-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoApp', '0002_rename_members_member_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
